import { Theme } from '../types/chess';

export const themes: Theme[] = [
  {
    type: 'ocean',
    name: 'Ocean',
    icon: 'Waves',
    lightSquare: 'bg-[#a5d8ff]',
    darkSquare: 'bg-[#0077cc]',
    background: 'bg-gradient-to-br from-blue-100 to-blue-200',
    accent: 'bg-blue-500',
    text: 'text-blue-900',
    notation: 'text-blue-700',
    container: "bg-white/10",
  },
  {
    type: 'classic',
    name: 'Classic',
    icon: 'Crown',
    lightSquare: 'bg-[#f0d9b5]',
    darkSquare: 'bg-[#b58863]',
    background: 'bg-gradient-to-br from-amber-50 to-amber-100',
    accent: 'bg-amber-500',
    text: 'text-gray-900',
    notation: 'text-gray-600',
    container: "bg-black/10",
  },
  {
    type: 'dark',
    name: 'Dark',
    icon: 'Moon',
    lightSquare: 'bg-[#525252]',
    darkSquare: 'bg-[#262626]',
    background: 'bg-gradient-to-br from-gray-900 to-gray-800',
    accent: 'bg-blue-500',
    text: 'text-gray-100',
    notation: 'text-gray-400',
    container: "bg-white/10",
  },
  {
    type: 'wooden',
    name: 'Wooden',
    icon: 'Trees',
    lightSquare: 'bg-[#e9c39c]',
    darkSquare: 'bg-[#8b4513]',
    background: 'bg-gradient-to-br from-[#deb887] to-[#d2691e]',
    accent: 'bg-[#8b4513]',
    text: 'text-[#3e2723]',
    notation: 'text-[#5d4037]',
    container: "bg-white/10",
  },
  {
    type: 'neon',
    name: 'Neon',
    icon: 'Zap',
    lightSquare: 'bg-[#2d1b4e]',
    darkSquare: 'bg-[#1a0b2e]',
    background: 'bg-gradient-to-br from-purple-900 to-black',
    accent: 'bg-purple-500',
    text: 'text-white',
    notation: 'text-purple-300',
    container: "bg-white/10",
  },
  {
    type: 'sunset',
    name: 'Sunset',
    icon: 'Sun',
    lightSquare: 'bg-[#ffb74d]',
    darkSquare: 'bg-[#e65100]',
    background: 'bg-gradient-to-br from-orange-100 to-rose-100',
    accent: 'bg-orange-500',
    text: 'text-orange-900',
    notation: 'text-orange-700',
    container: "bg-black/10",
  }
];